version: '3'

services:
  server:
    build: ./project
    image: master-image
    ports:
      - 5003:5000
    environment:
      - FLASK_APP=server:create_app()
      - FLASK_DEBUG=1
    volumes:
      - ./project:/app/iebc
      - ./data:/app/data
    command: flask run --host=0.0.0.0

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iebc
      - POSTGRES_PASSWORD=iebc
      - POSTGRES_DB=iebc_dev

  worker:
    image: master-image
    depends_on:
      - redis
    volumes:
      - ./project:/app/iebc
      - ./data:/app/data
    command: rq worker --name worker --url redis://redis:6379/0

  dashboard:
    image: master-image
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: rq-dashboard --port 5555 --redis-url redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
    postgres_data: