"""empty message

Revision ID: ba5cdf38abe1
Revises: 
Create Date: 2022-08-13 15:34:38.354688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5cdf38abe1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tallying',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polling_station', sa.String(length=128), nullable=False),
    sa.Column('raila', sa.String(length=128), nullable=True),
    sa.Column('ruto', sa.String(length=128), nullable=True),
    sa.Column('wajackoyah', sa.String(length=128), nullable=True),
    sa.Column('mwaure', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polling_station')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tallying')
    # ### end Alembic commands ###
